Project_BulletinBoard/BulletinBoard/apps/pages/urls.py
from django.urls import path
from .views import PostsList, PostDetail, PostDelete, PostCreate, PostEdit, ReplyCreate

app_name = 'pages'
urlpatterns = [
    path('', PostsList.as_view(), name='advert_all'),
    path('advert/<int:pk>', PostDetail.as_view(), name='advert_detail'),
    path('advert/<int:pk>/delete', PostDelete.as_view(), name='advert_delete'),
    path('advert/create', PostCreate.as_view(), name='advert_create'),
    path('advert/<int:pk>/edit', PostEdit.as_view(), name='advert_edit'),
    path('advert/<int:pk>/send_reply', ReplyCreate.as_view(), name='advert_reply'),
]

Project_BulletinBoard/BulletinBoard/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('staff/', include('emails.urls')),
    path('accounts/', include('allauth.urls')),
    path('profile/', include('profiles.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Project_BulletinBoard/BulletinBoard/apps/posts/models.py
import os

from django.conf import settings
from django.urls import reverse_lazy
from django.db import models


class Image(models.Model):
    image = models.ImageField()

    def delete_file(self):
        if self.image.name is None:
            return False
        FILEDIR = '/'.join(str(self.image).split('/')[0:-1])
        self.image.delete()
        HOMEDIR = str(settings.MEDIA_ROOT) + '/'
        if next(os.scandir(HOMEDIR + FILEDIR), None) is None:
            os.rmdir(HOMEDIR + FILEDIR)
        return True


class Advert(models.Model):
    TANKS = 'TK'
    DMAGERS = 'DD'
    HEALERS = 'HL'
    TRADERS = 'TD'
    GUILDMASTERS = 'GL'
    QUESTGIVERS = 'QG'
    BLACKSMITHS = 'BS'
    TANNERS = 'TN'
    POTIONMAKERS = 'PM'
    SPELLCASTERS = 'SC'
    CATEGORYS = [
        (TANKS, 'Танки'),
        (DMAGERS, 'ДД'),
        (HEALERS, 'Хилы'),
        (TRADERS, 'Торговцы'),
        (GUILDMASTERS, 'Гилдмастеры'),
        (QUESTGIVERS, 'Квестгиверы'),
        (BLACKSMITHS, 'Кузнецы'),
        (TANNERS, 'Кожевники'),
        (POTIONMAKERS, 'Зельевары'),
        (SPELLCASTERS, 'Мастера заклинаний'),
    ]
    
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )
    header = models.TextField(max_length=120, blank=False)
    text = models.TextField(blank=True)
    video = models.FileField(blank=True)
    image = models.ManyToManyField(Image, through='AdvertImage', blank=True)
    category = models.CharField(
        max_length=2,
        choices=CATEGORYS,
        default=TANKS
    )
    
    def delete_file(self):
        if self.video.name is None:
            return False
        FILEDIR = '/'.join(str(self.video).split('/')[0:-1])
        self.video.delete()
        HOMEDIR = str(settings.MEDIA_ROOT) + '/'
        if next(os.scandir(HOMEDIR + FILEDIR), None) is None:
            os.rmdir(HOMEDIR + FILEDIR)
        return True
    
    def __str__(self):
        return f'{self.id}. {self.header}'

    @property
    def category_name(self):
        return self.get_category_display()

    def get_absolute_url(self):
        return reverse_lazy('pages:advert_detail', args=[str(self.pk)])
    
    class Meta:
        ordering = ('-pk',)


class AdvertImage(models.Model):
    advert = models.ForeignKey(Advert, on_delete=models.CASCADE)
    image = models.ForeignKey(Image, on_delete=models.CASCADE)


class Reply(models.Model):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE
    )
    text = models.TextField()
    accept = models.BooleanField(default=False)
    advert = models.ForeignKey(Advert, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse_lazy('pages:advert_detail', args=[self.advert.pk])

Project_BulletinBoard/BulletinBoard/apps/posts/views.py
from django.shortcuts import render

# Create your views here.

Project_BulletinBoard/BulletinBoard/apps/pages/templates/pages/post_create.html
{% extends 'default.html' %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}
    <h2><span class="fas fa-scroll"></span> {{ title }}</h2>
    <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        {% for field in form.visible_fields %}
            <div class="mb-3">
                <label class="form-label my-auto" for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field.errors }}{{ field }}
            </div>
        {% endfor %}
        <div class="text-end pt-2 pb-5">
            <button class="btn btn-success btn-sm" type="submit">Сохранить <span class="far fa-edit"></span></button>
        </div>
    </form>
{% endblock content %}

Project_BulletinBoard/BulletinBoard/apps/pages/templates/pages/post_delete.html
{% extends 'default.html' %}

{% block title %}{{ post.header }}{% endblock title %}

{% block content %}
    <div class="row justify-content-center py-2">
        <div class="col-10">
            <h1 class="text-center text-danger">Удалить объявление?</h1>
        </div>
    </div>
    <div class="row justify-content-center py-2">
        <div class="col-10">
            <h2 class="text-center">{{ post.header }}</h2>
        </div>
    </div>
    <div class="row justify-content-center py-2">
        <div class="col-5"><p class="text-start my-1">Автор: {{ post.author.username }}</p></div>
        <div class="col-5"><p class="text-end my-1">Категория: {{ post.category_name }}</p></div>
    </div>
    <div class="row justify-content-center py-2">
        <div class="col-10"><p class="lead" style="text-indent: 1em; text-align: justify;">{{ post.text }}</p></div>
    </div>
    <div class="row justify-content-center pt-2 pb-5">
        <div class="col-10">
            <form method="POST" class="text-end">
                {% csrf_token %}
                <button class="btn btn-danger btn-sm" type="submit">Удалить <span class="far fa-trash-alt"></span></button>
            </form>
        </div>
    </div>
{% endblock content %}

Project_BulletinBoard/BulletinBoard/apps/pages/templates/pages/post_detail.html
{% extends 'default.html' %}
{% load allauth %}

{% block title %}{{ post.header }}{% endblock title %}

{% block content %}
<div class="row justify-content-center py-2">
    <div class="col-10">
        <h2 class="text-center">{{ post.header }}</h2>
    </div>
    <div class="col-10">
        {% include "pages/parts/carousel.html" %}
    </div>
</div>
<div class="row justify-content-center py-2">
    <div class="col-5"><p class="text-start my-1">Автор: {{ post.author.username }}</p></div>
    <div class="col-5"><p class="text-end my-1">Категория: {{ post.category_name }}</p></div>
</div>
<div class="row justify-content-center py-2">
    <div class="col-10"><p class="lead" style="text-indent: 1em; text-align: justify;">{{ post.text }}</p></div>
</div>
    {% if post.author.username == request.user.username %}
        <div class="row justify-content-center pt-2 pb-5">
            <div class="col-10 text-end">
                <a class="btn btn-success btn-sm" href="{% url 'pages:advert_edit' post.id %}">Редактировать <span class="far fa-edit"></span></a>
                <a class="btn btn-danger btn-sm" href="{% url 'pages:advert_delete' post.id %}">Удалить <span class="far fa-trash-alt"></span></a>
            </div>
        </div>
    {% elif user.is_authenticated %}
        <div class="row justify-content-center pt-2 pb-5">
        {% comment %} form reply {% endcomment %}
            <div class="col-10 text-end">
                <a class="btn btn-primary btn-sm" href="{% url 'pages:advert_reply' post.id %}">Откликнутся <span class="fas fa-reply"></span></a>
            </div>
        </div>
    {% endif %}
{% endblock content %}

Project_BulletinBoard/BulletinBoard/apps/pages/templates/pages/posts.html
{% extends 'default.html' %}
{% load allauth %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}
    <h2><span class="fas fa-scroll"></span> {{ title }}</h2>
    <hr>
    <div class="row justify-content-center">
        <div class="col-12 my-auto">
            <p class="text-end fs-5 my-auto">Всего объявлений: {{ paginator.count }}</p>
        </div>
    </div>
    <table class="table table-striped">
        <thead class="table-dark">
            <tr>
                <th scope="col">Заголовок</th>
                <th scope="col">Объявление</th>
            </tr>
        </thead>
        <tbody>
        {% if posts %}
            {% for post in posts %}
                {% include 'pages/parts/posts_tbody.html' %}
            {% endfor %}
        {% endif %}
        {% if not posts %}
            <tr>
                <td colspan="2"><p class="fs-5 my-auto">Объявлений нет</p></td>
            </tr>
        {% endif %}
        </tbody>
        </table>
        <div class="row justify-content-center pb-5">
            <div class="col-12 my-auto">
                {% if posts %}
                    {% include 'pages/parts/paginator.html' %}
                {% endif %}
            </div>
        </div>
{% endblock content %}