Project_BulletinBoard/BulletinBoard/apps/profiles/urls.py
from django.urls import path
from .views import RepliesList, action_reply

app_name = 'profiles'
urlpatterns = [
    path('<str:username>/replies', RepliesList.as_view(), name='replies'),
    path('<str:username>/<str:action>', action_reply, name='action_reply'),
]

Project_BulletinBoard/BulletinBoard/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('staff/', include('emails.urls')),
    path('accounts/', include('allauth.urls')),
    path('profile/', include('profiles.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Project_BulletinBoard/BulletinBoard/apps/profiles/models.py
from django.db import models

# Create your models here.

Project_BulletinBoard/BulletinBoard/apps/profiles/forms.py
from django import forms
from django.urls import reverse
from django.utils.safestring import mark_safe
from django.contrib.auth.models import User, Group
from allauth.account.forms import LoginForm, PasswordField, SignupForm
from allauth.utils import set_form_field_order


class CustomLoginForm(LoginForm):
    password = PasswordField(label='Пароль', autocomplete='current-password')
    password_widget = forms.PasswordInput(
            attrs={'placeholder': 'Пароль',
                   'class': 'form-control'},
        )
    password.widget = password_widget
    error_messages = {
        'account_inactive': 'Этот аккаунт в настоящее время неактивен.',
        'email_password_mismatch': 
            'Некорректный адрес электронной почты или пароль.'
        ,
        'username_password_mismatch': 
            'Некорректное имя пользователя или пароль.'
        ,
    }

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(CustomLoginForm, self).__init__(*args, **kwargs)
        login_widget = forms.TextInput(
            attrs={
                'type': 'email',
                'class': 'form-control',
                'placeholder': 'Электронная почта',
                'autocomplete': 'email',
            }
        )
        login_field = forms.EmailField(label='Электронная почта', widget=login_widget)
        self.fields['login'] = login_field
        set_form_field_order(self, ['login', 'password'])
        self.fields['password'].help_text = mark_safe(
            '<a href="{}">Забыли пароль?</a>').format(
                reverse('account_reset_password')
        )


class CustomSignupForm(SignupForm):
    
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(CustomSignupForm, self).__init__(*args, **kwargs)
        password1 = PasswordField(
            label='Пароль',
            autocomplete='new-password',
        )
        password1_widget = forms.PasswordInput(
            attrs={'placeholder': 'Пароль',
                   'class': 'form-control'},
        )
        password1.widget = password1_widget
        password2 = PasswordField(
                label='Пароль (повтор)', autocomplete='new-password'
            )
        password2_widget = forms.PasswordInput(
            attrs={'placeholder': 'Повторите пароль',
                   'class': 'form-control'},
        )
        password2.widget = password2_widget
        email = forms.EmailField(
            widget=forms.TextInput(
                attrs={
                    'type': 'email',
                    'class': 'form-control',
                    'placeholder': 'Электронная почта',
                    'autocomplete': 'email',
                }
            )
        )
        self.fields['email'] = email
        self.fields['email'].label = 'Электронная почта'
        self.fields['password1'] = password1
        self.fields['password2'] = password2
        set_form_field_order(self, ['email', 'password1', 'password2'])

    def save(self, request):
        user = super(CustomSignupForm, self).save(request)
        common_group = Group.objects.get_or_create(name='common')[0]
        common_group.user_set.add(user)
        username = User.objects.get(username=user)
        User.objects.filter(username=user).update(first_name=str(username))
        return user

Project_BulletinBoard/BulletinBoard/apps/profiles/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.decorators.csrf import csrf_protect

from .filters import ReplyFilter
from posts.models import Reply


class RepliesList(LoginRequiredMixin, ListView):
    # model = Reply
    # queryset = Reply.objects.prefetch_related('advert', 'author')
    template_name = 'profiles/replies.html'
    ordering = '-id'
    # paginate_by = 10
    # paginate_orphans = 4    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Отклики'
        context['filter'] = self.filterset
        return context

    def get_queryset(self):
        id = self.request.user.id
        # queryset = super().get_queryset().filter(advert__author__id=id)
        queryset = Reply.objects.filter(
            advert__author__id=id).prefetch_related('advert', 'author')
        self.filterset = ReplyFilter(
            self.request.GET,
            request=self.request,
            queryset=queryset
        )
        return self.filterset.qs


@login_required
@csrf_protect
def action_reply(request, username=None, action=None):
    def delete(id):
        reply = Reply.objects.get(pk=id)
        reply.delete()

    def accept(id):
        reply = Reply.objects.get(pk=id)
        reply.accept = True
        reply.save()

    ACTIONS = {
        'delete_reply': delete,
        'accept_reply': accept,
    }
    url = reverse_lazy('profiles:replies', args=[request.user.username])
    if request.user.username != username:
        return redirect(url)
    if action not in ACTIONS.keys():
        return redirect(url)
    if request.POST.get('reply_id') is not None:
        reply_id = request.POST.get("reply_id")
        ACTIONS[action](reply_id)
    return redirect(url)

Project_BulletinBoard/BulletinBoard/apps/profiles/templates/profiles/replies.html
{% extends 'default.html' %}
{% load allauth %}

{% block title %}{{ title }}{% endblock title %}

{% block content %}
    <h2><span class="fas fa-scroll"></span> {{ title }}</h2>
    <hr>
    <form class="row row-cols-auto my-2" method="GET">
        {% for field in filter.form %}
            <label class="form-label my-auto" for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field.errors }}{{ field }}
        {% endfor %}
        <input class="btn btn-info btn-sm mx-1 my-auto" type="submit" value="Найти">
    </form>
    <hr>
    <div class="row">
    {% for reply in filter.qs %}
    <div class="col-sm-3 mb-3 mb-sm-3">
        <div class="card">
            <div class="card-header"><a href="{{ reply.advert.get_absolute_url }}">{{ reply.advert|truncatechars:35 }}</a></div>
            <div class="card-body">
                <h6 class="card-title">Пользователь: {{ reply.author.username }}</h6>
                {% if reply.text|length > 32 %}
                    <p class="card-text">{{ reply.text|slice:":32" }}
                    <span class="text-primary text-decoration-underline" style="cursor: pointer;" data-bs-toggle="modal" data-bs-target="#modal{{ reply.pk }}">...</span></p>
                    <!-- Modal -->
                    <div class="modal fade" id="modal{{ reply.pk }}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                        <div class="modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable">
                            <div class="modal-content">
                            <div class="modal-header">
                            <h1 class="modal-title fs-5" id="staticBackdropLabel"><a href="{{ reply.advert.get_absolute_url }}">{{ reply.advert }}</a></h1>
                            <button type="button" class="btn-close mt-0 mb-auto" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <p class="card-text">{{ reply.text }}</p>
                            </div>
                            <div class="modal-footer">
                                {% if not reply.accept %}
                                <form method="POST" class="text-end d-inline" action="{% url "profiles:action_reply" user 'accept_reply' %}">
                                    {% csrf_token %}
                                    <input type="hidden" name="reply_id" value="{{ reply.pk }}">
                                    <button class="btn btn-sm btn-success" type="submit">Принять</button>
                                </form>
                                {% endif %}
                                {% load account %}
                                <form method="POST" class="text-end d-inline" action="{% url "profiles:action_reply" user 'delete_reply' %}">
                                    {% csrf_token %}
                                    <input type="hidden" name="reply_id" value="{{ reply.pk }}">
                                    <button class="btn btn-sm btn-danger" type="submit">Удалить</button>
                                </form>            
                            </div>
                        </div>
                        </div>
                    </div>
                {% else %}
                    <p class="card-text pb-3">{{ reply.text }}
                {% endif %}
            </div>
            <div class="card-footer text-body-secondary text-end">
                {% if not reply.accept %}
                    <form method="POST" class="text-end d-inline" action="{% url "profiles:action_reply" user 'accept_reply' %}">
                        {% csrf_token %}
                        <input type="hidden" name="reply_id" value="{{ reply.pk }}">
                        <button class="btn btn-sm btn-success" type="submit">Принять</button>
                    </form>
                {% endif %}
                {% load account %}
                <form method="POST" class="text-end d-inline" action="{% url "profiles:action_reply" user 'delete_reply' %}">
                    {% csrf_token %}
                    <input type="hidden" name="reply_id" value="{{ reply.pk }}">
                    <button class="btn btn-sm btn-danger" type="submit">Удалить</button>
                </form>
            </div>
        </div>
    </div>
    {% empty %}
    <div class="col-10">
        <p class="fs-5 my-auto">Откликов нет.</p>
    </div>
    {% endfor %}
    </div>
{% endblock content %}