Project_BulletinBoard/BulletinBoard/apps/pages/urls.py
from django.urls import path
from .views import PostsList, PostDetail, PostDelete, PostCreate, PostEdit, ReplyCreate

app_name = 'pages'
urlpatterns = [
    path('', PostsList.as_view(), name='advert_all'),
    path('advert/<int:pk>', PostDetail.as_view(), name='advert_detail'),
    path('advert/<int:pk>/delete', PostDelete.as_view(), name='advert_delete'),
    path('advert/create', PostCreate.as_view(), name='advert_create'),
    path('advert/<int:pk>/edit', PostEdit.as_view(), name='advert_edit'),
    path('advert/<int:pk>/send_reply', ReplyCreate.as_view(), name='advert_reply'),
]

Project_BulletinBoard/BulletinBoard/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('staff/', include('emails.urls')),
    path('accounts/', include('allauth.urls')),
    path('profile/', include('profiles.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Project_BulletinBoard/BulletinBoard/apps/pages/templates/pages/parts/carousel.html
{% if post.video or post.image.all %}
    <div id="carouselExampleIndicators" class="carousel slide" data-bs-interval="false">
            <div class="carousel-inner bg-secondary">
        {% if post.video %}
            <div class="carousel-item active" style="height: 500px;">
                <video class="d-block w-auto m-auto" controls autoplay height="500">
                    <source src="/media/{{ post.video }}" type="video/mp4">
                    Ваш браузер не поддерживает тэг video.
                </video>
            </div>
            {% if post.image.count %}
                {% for img in post.image.all %}
                    <div class="carousel-item" style="height: 500px;">
                        <img src="/media/{{ img.image }}" class="d-block w-auto m-auto" height="500" alt="santa">
                    </div>
                {% endfor %}
            {% endif %}
        {% elif post.image.all %}
            {% for img in post.image.all %}
                {% if forloop.first %}
                    <div class="carousel-item active" style="height: 500px;">
                        <img src="/media/{{ img.image }}" class="d-block w-auto m-auto" height="500" alt="santa">
                    </div>
                {% else %}
                    <div class="carousel-item" style="height: 500px;">
                        <img src="/media/{{ img.image }}" class="d-block w-auto m-auto" height="500" alt="santa">
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
        </div>
            <button class="carousel-control-prev" style="width: 5%;" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="w-10 carousel-control-next" style="width: 5%;" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
{% endif %}

Project_BulletinBoard/BulletinBoard/apps/pages/templates/pages/parts/paginator.html
{% if is_paginated %}
    <nav>
    <ul class="pagination my-auto">
    {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page=1">
                <span>первая</span>
            </a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                <span>{{ page_obj.previous_page_number }}</span>
            </a>
        </li>
    {% else %}
        <li class="page-item disabled">
            <a class="page-link">
                <span>первая</span>
            </a>
        </li>
        <li class="page-item disabled">
            <a class="page-link"><span class="fas fa-angle-double-left"></span></a>
        </li>
    {% endif %}
    <li class="page-item active">
        <a class="page-link">
            <span>{{ page_obj.number }}</span>
        </a>
    </li>
    {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                <span>{{ page_obj.next_page_number }}</span>
            </a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
                <span>последняя</span>
            </a>
        </li>
    {% else %}
        <li class="page-item disabled">
            <a class="page-link">
                <span class="fas fa-angle-double-right"></span>
            </a>
        </li>
        <li class="page-item disabled">
            <a class="page-link">
                <span>последняя</span>
            </a>
        </li>    
    {% endif %}
    </ul>
    </nav>
{% else %}
{% endif %}

Project_BulletinBoard/BulletinBoard/apps/pages/templates/pages/parts/posts_tbody.html
{% load pages_filters %}
<tr>
    <td><a href="{% url 'pages:advert_detail' post.id %}">{{ post.header|truncatechars:40 }}</a></td>
    <td>
        <div>{{ post.text|truncatewords:20 }}</div>
        <div class="text-start"><span class="fas fa-video"></span> {% if post.video %}1{% else %}0{% endif %} <span class="far fa-images"></span> {{ post.image.all.count }}
        <span class="far fa-comment-dots"></span> {% firstof reply_count|get_reply_count:post.id '0' %}</div>
    </td>
</tr>