Project_BulletinBoard/BulletinBoard/apps/emails/urls.py
from django.urls import path

from .views import News, NewsSuccess


app_name = 'emails'
urlpatterns = [
    path('newsletter/', News.as_view(), name='newsletter'),
    path('newsletter/send_success/', NewsSuccess.as_view(), name='send_success'),
]

Project_BulletinBoard/BulletinBoard/apps/pages/urls.py
from django.urls import path
from .views import PostsList, PostDetail, PostDelete, PostCreate, PostEdit, ReplyCreate

app_name = 'pages'
urlpatterns = [
    path('', PostsList.as_view(), name='advert_all'),
    path('advert/<int:pk>', PostDetail.as_view(), name='advert_detail'),
    path('advert/<int:pk>/delete', PostDelete.as_view(), name='advert_delete'),
    path('advert/create', PostCreate.as_view(), name='advert_create'),
    path('advert/<int:pk>/edit', PostEdit.as_view(), name='advert_edit'),
    path('advert/<int:pk>/send_reply', ReplyCreate.as_view(), name='advert_reply'),
]

Project_BulletinBoard/BulletinBoard/apps/profiles/urls.py
from django.urls import path
from .views import RepliesList, action_reply

app_name = 'profiles'
urlpatterns = [
    path('<str:username>/replies', RepliesList.as_view(), name='replies'),
    path('<str:username>/<str:action>', action_reply, name='action_reply'),
]

Project_BulletinBoard/BulletinBoard/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('staff/', include('emails.urls')),
    path('accounts/', include('allauth.urls')),
    path('profile/', include('profiles.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Project_BulletinBoard/templates/parts/footer.html
<footer class="fixed-bottom py-3 mt-auto bg-light">
    <div class="container">
      <p class="text-end my-1"><span class="text-muted far fa-copyright"> 2023 Place sticky footer content here.</span></p>
    </div>
</footer>

Project_BulletinBoard/templates/parts/header.html
{% load allauth %}
{% load staff_filters %}
<header class="p-3 text-bg-dark">
        <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                    <svg xmlns="http://www.w3.org/2000/svg" height="32"role="img" fill="currentColor" viewBox="0 0 384 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2023 Fonticons, Inc.--><path d="M368 32h-56a16 16 0 0 0 -16 16v48h-48V48a16 16 0 0 0 -16-16h-80a16 16 0 0 0 -16 16v48H88.1V48a16 16 0 0 0 -16-16H16A16 16 0 0 0 0 48v176l64 32c0 48.3-1.5 95-13.2 160h282.4C321.5 351 320 303.7 320 256l64-32V48a16 16 0 0 0 -16-16zM224 320h-64v-64a32 32 0 0 1 64 0zm144 128H16a16 16 0 0 0 -16 16v32a16 16 0 0 0 16 16h352a16 16 0 0 0 16-16v-32a16 16 0 0 0 -16-16z"/></svg>
                </a>
                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                    <li><a href="/" class="nav-link px-2 text-white">Объявления</a></li>
                    {% if user.is_authenticated %}
                        <li><a href="{% url "pages:advert_create" %}" class="nav-link px-2 text-white">Добавить объявление</a></li>
                        <li><a href="{% url "profiles:replies" user.username %}" class="nav-link px-2 text-white">Отклики</a></li>
                        {% if user|is_staff %}
                            <li><a href="{% url "emails:newsletter"%}" class="nav-link px-2 text-white">Отправить новость</a></li>
                        {% endif %}
                    {% endif %}
                </ul>
                <div class="text-end">
                    {% if user.is_authenticated %}
                        {% load account %}
                        <a class="btn btn-primary me-2" href="/accounts/2fa">Активировать 2FA <span class="fas fa-qrcode"></span></a>
                        <a class="btn btn-outline-light me-2" href="{% url 'account_logout' %}">{% user_display user %} <span class="fas fa-sign-out-alt"></span></a>
                    {% else %}
                        <a class="btn btn-outline-light me-2" href="{% url 'account_login' %}">Вход <span class="fas fa-sign-in-alt"></span></a>
                        <a class="btn btn-warning" href="{% url 'account_signup' %}">Регистрация <span class="fas fa-user-plus"></span></a>
                    {% endif %}
                </div>
            </div>
        </div>
</header>
